# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Log_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(492, 200)
        Dialog.setMinimumSize(QtCore.QSize(492, 200))
        Dialog.setMaximumSize(QtCore.QSize(492, 200))
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 150, 351, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.Log_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Log_Button.setObjectName("Log_Button")
        self.horizontalLayout_4.addWidget(self.Log_Button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.Sign = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Sign.setObjectName("Sign")
        self.horizontalLayout_4.addWidget(self.Sign)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.Cancel_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Cancel_Button.setObjectName("Cancel_Button")
        self.horizontalLayout_4.addWidget(self.Cancel_Button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 461, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.PassWord_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.PassWord_Edit.setFont(font)
        self.PassWord_Edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassWord_Edit.setObjectName("PassWord_Edit")
        self.horizontalLayout_7.addWidget(self.PassWord_Edit)
        self.PassWordShow_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.PassWordShow_Button.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);\n"
"image: url(:/other/Other/button-on.png);\n"
"}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.PassWordShow_Button.setText("")
        self.PassWordShow_Button.setObjectName("PassWordShow_Button")
        self.horizontalLayout_7.addWidget(self.PassWordShow_Button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 461, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.ID_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.ID_Edit.setFont(font)
        self.ID_Edit.setObjectName("ID_Edit")
        self.horizontalLayout_9.addWidget(self.ID_Edit)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Tips = QtWidgets.QLabel(Dialog)
        self.Tips.setGeometry(QtCore.QRect(120, 120, 271, 21))
        self.Tips.setText("")
        self.Tips.setObjectName("Tips")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 20, 31, 31))
        self.label_7.setStyleSheet("image: url(:/other/Other/数据探索.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Log_Button.setText(_translate("Dialog", "登录"))
        self.Sign.setText(_translate("Dialog", "注册"))
        self.Cancel_Button.setText(_translate("Dialog", "取消"))
        self.label_3.setText(_translate("Dialog", "密码："))
        self.label_5.setText(_translate("Dialog", "账号："))
        self.label_8.setText(_translate("Dialog", "    "))
        self.label.setText(_translate("Dialog", "交通场景检测系统登录"))
from UI_core import images_rc
import json


class UI_Log(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

    def Log_Function(self,new_Weight):
        path = r'./data/user_data/users.json'
        with open(path,'r') as f:
            users_data = json.load(f)
        input_ID = self.ui.ID_Edit.text()
        input_PassWord = self.ui.PassWord_Edit.text()
        if input_ID not in users_data.keys():
            self.ui.Tips.setText('账号不存在！！！')
        elif input_PassWord != users_data[input_ID]:
            self.ui.Tips.setText('密码错误！！！')
        else:
            self.close()
            new_Weight.show()

    def ShowPassWord(self):
        self.ui.PassWord_Edit.setEchoMode(QtWidgets.QLineEdit.Normal)
    def HidePassWord(self):
        self.ui.PassWord_Edit.setEchoMode(QtWidgets.QLineEdit.Password)