# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sign_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sign_UI(object):
    def setupUi(self, Sign_UI):
        Sign_UI.setObjectName("Sign_UI")
        Sign_UI.resize(520, 343)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Sign_UI)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 260, 351, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.Log_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Log_Button.setObjectName("Log_Button")
        self.horizontalLayout_4.addWidget(self.Log_Button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.Cancel_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Cancel_Button.setObjectName("Cancel_Button")
        self.horizontalLayout_4.addWidget(self.Cancel_Button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(Sign_UI)
        self.label.setGeometry(QtCore.QRect(200, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(Sign_UI)
        self.label_7.setGeometry(QtCore.QRect(140, 30, 31, 31))
        self.label_7.setStyleSheet("\n"
"image: url(:/other/Other/数据探索.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Sign_UI)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 130, 461, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.PassWord_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.PassWord_Edit.setFont(font)
        self.PassWord_Edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassWord_Edit.setObjectName("PassWord_Edit")
        self.horizontalLayout_7.addWidget(self.PassWord_Edit)
        self.PassWordShow_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.PassWordShow_Button.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);\n"
"image: url(:/other/Other/button-on.png);\n"
"}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.PassWordShow_Button.setText("")
        self.PassWordShow_Button.setObjectName("PassWordShow_Button")
        self.horizontalLayout_7.addWidget(self.PassWordShow_Button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.Tips = QtWidgets.QLabel(Sign_UI)
        self.Tips.setGeometry(QtCore.QRect(120, 220, 271, 21))
        self.Tips.setText("")
        self.Tips.setObjectName("Tips")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Sign_UI)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 80, 461, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.ID_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.ID_Edit.setFont(font)
        self.ID_Edit.setObjectName("ID_Edit")
        self.horizontalLayout_9.addWidget(self.ID_Edit)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Sign_UI)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 170, 461, 41))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.PassWord_Edit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.PassWord_Edit_4.setFont(font)
        self.PassWord_Edit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassWord_Edit_4.setObjectName("PassWord_Edit_4")
        self.horizontalLayout_11.addWidget(self.PassWord_Edit_4)
        self.PassWordShow_Button_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.PassWordShow_Button_4.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);\n"
"image: url(:/other/Other/button-on.png);\n"
"}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.PassWordShow_Button_4.setText("")
        self.PassWordShow_Button_4.setObjectName("PassWordShow_Button_4")
        self.horizontalLayout_11.addWidget(self.PassWordShow_Button_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)

        self.retranslateUi(Sign_UI)
        QtCore.QMetaObject.connectSlotsByName(Sign_UI)

    def retranslateUi(self, Sign_UI):
        _translate = QtCore.QCoreApplication.translate
        Sign_UI.setWindowTitle(_translate("Sign_UI", "Dialog"))
        self.Log_Button.setText(_translate("Sign_UI", "注册"))
        self.Cancel_Button.setText(_translate("Sign_UI", "取消"))
        self.label.setText(_translate("Sign_UI", "账号注册"))
        self.label_3.setText(_translate("Sign_UI", "输入密码："))
        self.label_5.setText(_translate("Sign_UI", "输入账号："))
        self.label_8.setText(_translate("Sign_UI", "    "))
        self.label_9.setText(_translate("Sign_UI", "确认密码："))
from UI_core import images_rc


class UI_Sign(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_Sign_UI()
        self.ui.setupUi(self)

    def Sign_Function(self):
        import os
        import json
        path = os.path.abspath(r'./data/user_data/users.json')
        if os.path.exists(path):
            with open(path,'r') as f:
                users_data = json.load(f)
        else:
            users_data = {}
        ID_data = self.ui.ID_Edit.text()
        Password1_data = self.ui.PassWord_Edit.text()
        Password2_data = self.ui.PassWord_Edit_4.text()
        if ID_data in users_data.keys():
            self.ui.Tips.setText('账号已存在！！！')
        elif ID_data == '' or Password1_data == '' or Password2_data == '':
            self.ui.Tips.setText('信息未填写完整！！！！')
        elif Password1_data !=Password2_data:
            self.ui.Tips.setText('两次密码输入不一致！！！')
        else:
            users_data[ID_data] = Password1_data
            with open(path,'w') as b:
                json.dump(users_data,b)
            self.close()

    def ShowEdit1PassWord(self):
        self.ui.PassWord_Edit.setEchoMode(QtWidgets.QLineEdit.Normal)
    def ShowEdit2PassWord(self):
        self.ui.PassWord_Edit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
    def HideEdit1PassWord(self):
        self.ui.PassWord_Edit.setEchoMode(QtWidgets.QLineEdit.Password)
    def HideEdit2PassWord(self):
        self.ui.PassWord_Edit_4.setEchoMode(QtWidgets.QLineEdit.Password)
